spring.application.name=ragapp-prod
server.address=0.0.0.0
server.port=8080

app.jwt.secret=${JWT_SECRET}
google.api.key=${GEMINI_API_KEY}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.idle-timeout=300000

# spring.jpa.hibernate.ddl-auto=validate 
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=false 
spring.jpa.properties.hibernate.format_sql=false

app.upload.max-size=50MB
app.upload.allowed-types=csv,xlsx,txt,pdf,docx

management.endpoints.web.exposure.include=health,info,metrics

logging.level.root=WARN
logging.level.com.example.ragapp=INFO
logging.level.org.springframework.web=INFO